### ISSUE TITLE
ItemDataBinding class is missing

### ISSUE THREAD

**Issue by vikrantshroti** [phunware/blog-android-clean-coding-approach#1]
I searched for all files, but could not find ItemDataBinding 
update : it was in xml (my bad)  :smile:

**Comment by KeenanWannop1** [comment]
Where? I still can't find it.

**Comment by grasmussen-phunware** [comment]
Hello everyone,  

ItemDataBinding is generated in the build process.  I recommend cleaning, building, and running the project on the device.  After the app is running on the device, you'll see that Android Studio no longer has red underlines for ItemDataBinding.   If you go in the build directory, you'll generated code that you can explore.

Best,

Gregory


The screenshot shows an example of some of the generated code.
![screen shot 2019-02-04 at 10 07 54 am](https://user-images.githubusercontent.com/25698296/52233903-26dfda00-2875-11e9-8fdd-8a3d55190107.png)
